import type { ListingContent, Marketplace } from "@/types";
import { getMarketplaceProfile } from "@/lib/marketplace/registry";
import { stripHtml } from "@/lib/utils/sanitize";

export function formatListingForClipboard(content: ListingContent, marketplace: Marketplace): string {
  const profile = getMarketplaceProfile(marketplace);
  const sections: string[] = [];

  sections.push(`=== ${profile.name} Listing ===`);
  sections.push("");

  // Title
  if (content.title) {
    sections.push("TITLE");
    sections.push(content.title);
    sections.push("");
  }

  // Subtitle (eBay)
  if (content.subtitle) {
    sections.push("SUBTITLE");
    sections.push(content.subtitle);
    sections.push("");
  }

  // Bullets
  if (content.bullets && content.bullets.length > 0) {
    sections.push("BULLET POINTS");
    content.bullets.forEach((bullet, i) => {
      sections.push(`${i + 1}. ${stripHtml(bullet)}`);
    });
    sections.push("");
  }

  // Shelf Description (Walmart)
  if (content.shelf_description) {
    sections.push("SHELF DESCRIPTION");
    sections.push(stripHtml(content.shelf_description));
    sections.push("");
  }

  // Description
  if (content.description) {
    sections.push("DESCRIPTION");
    sections.push(stripHtml(content.description));
    sections.push("");
  }

  // Backend Keywords (Amazon)
  if (content.backend_keywords) {
    sections.push("BACKEND SEARCH TERMS");
    sections.push(content.backend_keywords);
    sections.push("");
  }

  // SEO (Shopify)
  if (content.seo_title) {
    sections.push("SEO TITLE");
    sections.push(content.seo_title);
    sections.push("");
  }
  if (content.meta_description) {
    sections.push("META DESCRIPTION");
    sections.push(content.meta_description);
    sections.push("");
  }

  // Tags
  if (content.tags && content.tags.length > 0) {
    sections.push("TAGS");
    sections.push(content.tags.join(", "));
    sections.push("");
  }

  // Item Specifics (eBay)
  if (content.item_specifics && Object.keys(content.item_specifics).length > 0) {
    sections.push("ITEM SPECIFICS");
    Object.entries(content.item_specifics).forEach(([key, value]) => {
      sections.push(`${key}: ${value}`);
    });
    sections.push("");
  }

  // Attributes (Walmart)
  if (content.attributes && Object.keys(content.attributes).length > 0) {
    sections.push("ATTRIBUTES");
    Object.entries(content.attributes).forEach(([key, value]) => {
      sections.push(`${key}: ${value}`);
    });
    sections.push("");
  }

  // Photo Recommendations
  if (content.photo_recommendations && content.photo_recommendations.length > 0) {
    sections.push("PHOTO RECOMMENDATIONS");
    content.photo_recommendations.forEach((photo) => {
      sections.push(`Slot ${photo.slot} (${photo.type}): ${photo.description}`);
      photo.tips.forEach((tip) => {
        sections.push(`  • ${tip}`);
      });
    });
    sections.push("");
  }

  sections.push("---");
  sections.push("Generated by SellerAide");

  return sections.join("\n");
}
